### ISSUE TITLE
java.lang.NoClassDefFoundError: com/google/common/cache/RemovalNotification when stopping ShardedRocksDBService 

### ISSUE THREAD

**Issue by jnioche** [crawler-commons/url-frontier#58]
jnioche@node1:/data$ java -Xmx5G -XX:+UseG1GC -Djava.net.preferIPv4Stack=true -cp urlfrontier-service-*.jar crawlercommons.urlfrontier.service.URLFrontierServer -h $Node3  -s 9100 rocksdb.path=/data/rocksdb implementation=crawlercommons.urlfrontier.service.rocksdb.ShardedRocksDBService nodes=$Node1:7071,$Node2:7071,$Node3:7071 -c config.ini > frontier.log
^CException in thread "Thread-1" java.lang.NoClassDefFoundError: com/google/common/cache/RemovalNotification
        at com.google.common.cache.LocalCache$Segment.enqueueNotification(LocalCache.java:2527)
        at com.google.common.cache.LocalCache$Segment.removeValueFromChain(LocalCache.java:3147)
        at com.google.common.cache.LocalCache$Segment.removeEntry(LocalCache.java:3314)
        at com.google.common.cache.LocalCache$Segment.expireEntries(LocalCache.java:2511)
        at com.google.common.cache.LocalCache$Segment.runLockedCleanup(LocalCache.java:3368)
        at com.google.common.cache.LocalCache$Segment.preWriteCleanup(LocalCache.java:3350)
        at com.google.common.cache.LocalCache$Segment.clear(LocalCache.java:3104)
        at com.google.common.cache.LocalCache.clear(LocalCache.java:4137)
        at com.google.common.cache.LocalCache$LocalManualCache.invalidateAll(LocalCache.java:4725)
        at crawlercommons.urlfrontier.service.cluster.DistributedFrontierService.close(DistributedFrontierService.java:357)
        at crawlercommons.urlfrontier.service.rocksdb.ShardedRocksDBService.close(ShardedRocksDBService.java:80)
        at crawlercommons.urlfrontier.service.URLFrontierServer.stop(URLFrontierServer.java:215)
        at crawlercommons.urlfrontier.service.URLFrontierServer.lambda$registerShutdownHook$0(URLFrontierServer.java:200)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: com.google.common.cache.RemovalNotification
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 14 more

**Comment by jnioche** [comment]
can't reproduce
