### ISSUE TITLE
Forwarded putURLs writes share an unsynchronized StreamObserver across client streams

### ISSUE THREAD

**Issue by jnioche** [crawler-commons/url-frontier#69]
In `DistributedFrontierService.putURLs`, items whose partition is not the local node are forwarded through a per-partition `StreamObserver` held in `observercache`:

```java
observercache.getUnchecked(partition)
        .onNext(URLItem.newBuilder(value).setID(token).build());
```

`observercache` is a field of the service singleton, so **every concurrent `putURLs` client stream shares the same outgoing observer for a given partition**. gRPC serializes callbacks within a single server stream, but not across streams, so two clients sending to the same partition at the same time call `onNext` concurrently on the same unsynchronized `ClientCallStreamObserver`. That corrupts netty's write path and surfaces as the `IllegalReferenceCountException` / `UnpooledSlicedByteBuf(freed)` crash recorded below.

Note the asymmetry: the client-facing observer *is* protected, via `SynchronizedStreamObserver.wrapping(...)`, but the forwarding one never got the same treatment.

### Remaining work

1. **Serialize writes to the forwarding observer** — wrap each per-partition observer in `SynchronizedStreamObserver`, or serialize per partition some other way. This is a live bug reachable today with multiple concurrent clients.
2. **Optionally honour flow control on the forwarding call** — `isReady` / `onReadyHandler`. Buffering is currently bounded only indirectly, by `putURLsMaxInFlight` per stream and the one-minute `inprocesscache` expiry.

### Original framing, and why it changed

This issue was opened as "use a threadpool for all the writes, including the ones to another Frontier instance and not just the local ones". Since then:

- **Local writes already go through the pool.** `putURLItem` is submitted to `writeExecutorService`, with `RejectedExecutionException` handled and `AsyncCompletion` keeping the response stream open until every item has landed. That half of the original title is done.
- **Moving the forwards onto the pool is probably not what we want.** `onNext` on an async client stub doesn't block on the network, it queues into netty — so offloading it buys little, while widening the race above from cross-stream to per-item. The threadpool is the right tool for the local RocksDB write; the forward needs synchronization, not a pool.

Two other problems visible in the original report have since been fixed independently: forwarded items now travel under a unique correlation token rather than the client-supplied ID (which could legitimately repeat), and `inprocesscache` has a cleanup heartbeat so items whose ack never comes back are failed rather than left hanging.

<details>
<summary>Original report (Oct 2022): throughput before, crash after moving forwards onto the pool</summary>

**Before**

_Sent: 25948931
Acked: 25948931
OK: 20320327
Skipped: 5628604
Failed: 0
Total time: 2547400 msec
Average OPS: 10188_

**After**

CRASHED WITH

```
14:39:29.457 [grpc-default-worker-ELG-3-3] WARN  i.g.n.s.i.n.util.ReferenceCountUtil - Failed to release a message: UnpooledSlicedByteBuf(freed)
io.grpc.netty.shaded.io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.grpc.netty.shaded.io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:83)
	at io.grpc.netty.shaded.io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:147)
	at io.grpc.netty.shaded.io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101)
	at io.grpc.netty.shaded.io.netty.buffer.CompositeByteBuf$Component.free(CompositeByteBuf.java:1959)
	at io.grpc.netty.shaded.io.netty.buffer.CompositeByteBuf.deallocate(CompositeByteBuf.java:2264)
	at io.grpc.netty.shaded.io.netty.buffer.AbstractReferenceCountedByteBuf.handleRelease(AbstractReferenceCountedByteBuf.java:111)
	at io.grpc.netty.shaded.io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101)
	at io.grpc.netty.shaded.io.netty.buffer.AbstractDerivedByteBuf.release0(AbstractDerivedByteBuf.java:98)
	at io.grpc.netty.shaded.io.netty.buffer.AbstractDerivedByteBuf.release(AbstractDerivedByteBuf.java:94)
	at io.grpc.netty.shaded.io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:90)
	at io.grpc.netty.shaded.io.netty.util.ReferenceCountUtil.safeRelease(ReferenceCountUtil.java:116)
	at io.grpc.netty.shaded.io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:271)
	at io.grpc.netty.shaded.io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:352)
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollStreamChannel.writeBytesMultiple(AbstractEpollStreamChannel.java:305)
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollStreamChannel.doWriteMultiple(AbstractEpollStreamChannel.java:510)
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollStreamChannel.doWrite(AbstractEpollStreamChannel.java:422)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931)
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.flush0(AbstractEpollChannel.java:557)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895)
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:197)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:967)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannel.flush(AbstractChannel.java:254)
	at io.grpc.netty.shaded.io.grpc.netty.WriteQueue.flush(WriteQueue.java:147)
	at io.grpc.netty.shaded.io.grpc.netty.WriteQueue.access$000(WriteQueue.java:34)
	at io.grpc.netty.shaded.io.grpc.netty.WriteQueue$1.run(WriteQueue.java:46)
	at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

</details>

**Comment by jnioche** [comment]
This issue is still open
